
name: kaaki_kaburu
description: A news app in Telugu with location and admin panel
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  cloud_firestore: ^4.0.0
  firebase_auth: ^4.0.0
  geolocator: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
